#                                         BML  Assginment-I

NAME : S.JANANE                     

YEAR : 2nd - "A"
    
Topic : Data Preprocessing in ML

In [123]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer 
from sklearn.preprocessing import LabelEncoder, OneHotEncoder 
from sklearn.model_selection import train_test_split 
from sklearn.preprocessing import StandardScaler 

In [124]:
dataset = pd.read_csv('C:/Users/Janane Sundar/Documents/bml/stack_price.csv')
dataset

Date        Open        High         Low       Close   Adj Close  \
0     29-06-2010   19.000000   25.000000   17.540001   23.889999   23.889999   
1     30-06-2010   25.790001   30.420000   23.299999   23.830000   23.830000   
2     01-07-2010   25.000000   25.920000   20.270000   21.959999         NaN   
3     02-07-2010   23.000000   23.100000   18.709999   19.200001   19.200001   
4     06-07-2010   20.000000   20.000000   15.830000         NaN   16.110001   
...          ...         ...         ...         ...         ...         ...   
2411  28-01-2020  568.489990  576.809998  558.080017  566.900024  566.900024   
2412  29-01-2020  575.690002  589.799988  567.429993  580.989990  580.989990   
2413  30-01-2020  632.419983  650.880005  618.000000  640.809998  640.809998   
2414  31-01-2020  640.000000  653.000000  632.520020  650.570007  650.570007   
2415  03-02-2020  673.690002  786.140015  673.520020  780.000000  780.000000   

          Volume  
0     18766300.0  
1     17187100.0  
2      8218800.0  
3      5139800.0  
4            NaN  
...          ...  
2411  11788500.0  
2412  17801500.0  
2413  29005700.0  
2414  15719300.0  
2415  47065000.0  

[2416 rows x 7 columns]

In [125]:
X = dataset.iloc[:, :-1].values
X

array([['29-06-2010', 19.0, 25.0, 17.540001, 23.889999, 23.889999],
       ['30-06-2010', 25.790001, 30.42, 23.299999, 23.83, 23.83],
       ['01-07-2010', 25.0, 25.92, 20.27, 21.959999, nan],
       ...,
       ['30-01-2020', 632.419983, 650.880005, 618.0, 640.809998,
        640.809998],
       ['31-01-2020', 640.0, 653.0, 632.52002, 650.570007, 650.570007],
       ['03-02-2020', 673.690002, 786.140015, 673.52002, 780.0, 780.0]],
      dtype=object)

In [126]:
print(dataset.isnull().sum())

Date         0
Open         0
High         1
Low          2
Close        1
Adj Close    1
Volume       2
dtype: int64


In [127]:
dataset.dropna(inplace=True)
dataset

Date        Open        High         Low       Close   Adj Close  \
0     29-06-2010   19.000000   25.000000   17.540001   23.889999   23.889999   
1     30-06-2010   25.790001   30.420000   23.299999   23.830000   23.830000   
3     02-07-2010   23.000000   23.100000   18.709999   19.200001   19.200001   
5     07-07-2010   16.400000   16.629999   14.980000   15.800000   15.800000   
6     08-07-2010   16.139999   17.520000   15.570000   17.459999   17.459999   
...          ...         ...         ...         ...         ...         ...   
2411  28-01-2020  568.489990  576.809998  558.080017  566.900024  566.900024   
2412  29-01-2020  575.690002  589.799988  567.429993  580.989990  580.989990   
2413  30-01-2020  632.419983  650.880005  618.000000  640.809998  640.809998   
2414  31-01-2020  640.000000  653.000000  632.520020  650.570007  650.570007   
2415  03-02-2020  673.690002  786.140015  673.520020  780.000000  780.000000   

          Volume  
0     18766300.0  
1     17187100.0  
3      5139800.0  
5      6921700.0  
6      7711400.0  
...          ...  
2411  11788500.0  
2412  17801500.0  
2413  29005700.0  
2414  15719300.0  
2415  47065000.0  

[2410 rows x 7 columns]

In [128]:
from sklearn.impute import SimpleImputer

In [129]:
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')

In [130]:
x=dataset[['High','Low','Close']].values
x

array([[ 25.      ,  17.540001,  23.889999],
       [ 30.42    ,  23.299999,  23.83    ],
       [ 23.1     ,  18.709999,  19.200001],
       ...,
       [650.880005, 618.      , 640.809998],
       [653.      , 632.52002 , 650.570007],
       [786.140015, 673.52002 , 780.      ]])

In [131]:
imputer=imputer.fit(x[:,1:3])

In [132]:
x[:,1:3]=imputer.transform(x[:,1:3])
x

array([[ 25.      ,  17.540001,  23.889999],
       [ 30.42    ,  23.299999,  23.83    ],
       [ 23.1     ,  18.709999,  19.200001],
       ...,
       [650.880005, 618.      , 640.809998],
       [653.      , 632.52002 , 650.570007],
       [786.140015, 673.52002 , 780.      ]])

In [133]:
from sklearn.preprocessing import LabelEncoder

In [134]:
label_encode_x=LabelEncoder()
label_encode_y=LabelEncoder()

In [135]:
label_encode_x

LabelEncoder()

In [136]:
x[:,0]=label_encode_x.fit_transform(x[:,0])
x

array([[ 123.      ,   17.540001,   23.889999],
       [ 315.      ,   23.299999,   23.83    ],
       [  73.      ,   18.709999,   19.200001],
       ...,
       [2121.      ,  618.      ,  640.809998],
       [2122.      ,  632.52002 ,  650.570007],
       [2123.      ,  673.52002 ,  780.      ]])

In [137]:
label_encode_x.classes_

array([ 16.629999,  17.52    ,  17.9     , ..., 650.880005, 653.      ,
       786.140015])

In [138]:
y=dataset[['Date']].values
y

array([['29-06-2010'],
       ['30-06-2010'],
       ['02-07-2010'],
       ...,
       ['30-01-2020'],
       ['31-01-2020'],
       ['03-02-2020']], dtype=object)

In [139]:
y=label_encode_y.fit_transform(y)
y

C:\Users\Janane Sundar\Anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([2240, 2313,  110, ..., 2295, 2368,  165])

In [140]:
from sklearn.model_selection import train_test_split

In [141]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=1)

In [142]:
x_train

array([[1678.      ,  288.769989,  297.859985],
       [ 119.      ,   24.33    ,   24.82    ],
       [1310.      ,  235.669998,  238.089996],
       ...,
       [1398.      ,  245.580002,  249.100006],
       [ 248.      ,   27.879999,   28.43    ],
       [1404.      ,  247.039993,  252.139999]])

In [143]:
x_test

array([[1520.      ,  261.200012,  261.5     ],
       [ 473.      ,   34.540001,   34.98    ],
       [1933.      ,  325.      ,  346.      ],
       ...,
       [1980.      ,  343.73999 ,  344.570007],
       [1760.      ,  308.      ,  314.070007],
       [ 760.      ,  176.990005,  178.970001]])

In [144]:
y_train

array([1987, 1167, 2358, ...,  938,  983, 1882])

In [145]:
y_test

array([1288, 1439, 2046,    1, 1576,  778,  799,  874, 2091, 2365,  714,
       1963, 1103, 1560, 1027, 1724,  608,  723, 2319,  905,  668,  624,
        907,  429,  484, 1974, 1299,   80,  724, 1202, 2261, 1294, 2243,
       2206, 1302, 1955, 1002, 2302, 1615,  165, 2271, 1978,  450, 1325,
       1921, 1837, 2082, 1943, 1421, 1609,  382, 2350,  842, 2381,  879,
       2253, 2407,  436,  737, 1701,  958,  898, 1024, 1266,  707, 1162,
        716,  299, 2044,  304,  125, 1556,  802, 1500, 1858, 1447, 1305,
       1555, 2332, 2262,  692, 2280,  516,  465,  338, 1563, 2107,  673,
       1139, 1854,  617,  943,  409, 1313,  843, 1581, 2070,  890, 2213,
        459, 1048, 1293, 1013, 1354,  698, 1110,   96,  527,  164, 1323,
       1729, 1007, 1797,  107,   63, 2015,  566,  138,  602,  722, 2105,
       1528,  806, 2380,  281, 1869, 1850, 1829, 1773, 1215, 1055, 1085,
       2272,  129,  701,   95,   59, 1616, 1107,  650, 1036, 1208, 1792,
       2127, 1700,  396,  403, 1587,  171, 1123,  3

In [146]:
from sklearn.preprocessing import StandardScaler

In [147]:
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.fit_transform(x_test)
print(x_train)
print(x_test)

[[ 1.04389421  0.89922851  0.93061656]
 [-1.4569502  -1.35659172 -1.35799516]
 [ 0.45357301  0.44625605  0.42962658]
 ...
 [ 0.59473678  0.53079389  0.5219121 ]
 [-1.25001695 -1.32630825 -1.32773626]
 [ 0.60436158  0.54324843  0.54739322]]
[[ 0.82045197  0.67757178  0.63350443]
 [-0.92154643 -1.29218871 -1.28693515]
 [ 1.50760129  1.23201761  1.34989656]
 ...
 [ 1.58579988  1.39487515  1.33777306]
 [ 1.21976393  1.08428123  1.07919365]
 [-0.44403589 -0.05424476 -0.066186  ]]


In [148]:
dataset

Date        Open        High         Low       Close   Adj Close  \
0     29-06-2010   19.000000   25.000000   17.540001   23.889999   23.889999   
1     30-06-2010   25.790001   30.420000   23.299999   23.830000   23.830000   
3     02-07-2010   23.000000   23.100000   18.709999   19.200001   19.200001   
5     07-07-2010   16.400000   16.629999   14.980000   15.800000   15.800000   
6     08-07-2010   16.139999   17.520000   15.570000   17.459999   17.459999   
...          ...         ...         ...         ...         ...         ...   
2411  28-01-2020  568.489990  576.809998  558.080017  566.900024  566.900024   
2412  29-01-2020  575.690002  589.799988  567.429993  580.989990  580.989990   
2413  30-01-2020  632.419983  650.880005  618.000000  640.809998  640.809998   
2414  31-01-2020  640.000000  653.000000  632.520020  650.570007  650.570007   
2415  03-02-2020  673.690002  786.140015  673.520020  780.000000  780.000000   

          Volume  
0     18766300.0  
1     17187100.0  
3      5139800.0  
5      6921700.0  
6      7711400.0  
...          ...  
2411  11788500.0  
2412  17801500.0  
2413  29005700.0  
2414  15719300.0  
2415  47065000.0  

[2410 rows x 7 columns]